version: '3.7'
services:
  qubic:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - type: volume
        source: qubicdata
        target: /app
      - type: bind
        source: ./app/appsettings.json
        target: /app/appsettings.json
    restart: unless-stopped

volumes:
  qubicdata: